version: '2'

services:
  mongodb_courses_organizations:
    image: mongo:latest
    restart: always
    container_name: "mongodb_courses_organizations"
    ports:
      - "27018:27017"
# First node of the first Tomcat virtual host.
  tomcat:
    restart: always
    image: tomcat
    ports:
      - "8091:8090"
    volumes:
      - ../courses_organizations/target/courses_organizations-microservice-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/courses_organizations-microservice.war
    links:
      - mongodb_courses_organizations:mongodb_courses_organizations
    #depends_on:
     # - "db"
