version: '2'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: monodb_courses_organizations
    ports:
      - "27017:27018"
# First node of the first Tomcat virtual host.
  tomcat:
    restart: always
    image: tomcat
    ports:
      - "8080:8090"
    volumes:
      - ../courses/target/courses-microservice-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/courses-microservice.war
    links:
      - mongodb:mongodb
    #depends_on:
     # - "db"
